image: Visual Studio 2015
configuration: Release

environment:
  matrix:
   - target: 360tools_vs2010.sln
   - target: 360tools_conv_vs2010.vcxproj
   - target: 360tools_metric_vs2010.vcxproj
   - target: 360tools_conv_vs2010.vcxproj

build_script:
 - msbuild c:\projects\360tools\build\x86_windows\%target%
 
artifacts:
 - path: \**\360tools*.exe
 - path: \**\360tools*.lib
